spring:
  profiles:
    active: dev
    default: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
qiniu:
  ak: ${QINIU_AK:lingxi}
  sk: ${QINIU_SK:lingxi}
  bucket: ${QINIU_BUCKET:upload}